
name: MOVA Thin Core Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i -D ajv ajv-formats ajv-cli
      - name: Validate envelope: positive
        run: npx ajv validate -c ajv-formats -s schemas/envelope.3.3.schema.json -d "tests/conformance/envelope/positive/*.json" --strict=true
      - name: Validate envelope: negative (expect fail)
        run: bash scripts/validate_negative.sh schemas/envelope.3.3.schema.json tests/conformance/envelope/negative
      - name: Validate route: positive
        run: npx ajv validate -c ajv-formats -s schemas/route.1.0.schema.json -d "tests/conformance/route
