
name: MOVA Thin Core Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i -D ajv ajv-formats ajv-cli
      - name: Validate envelope: positive
        run: npx ajv validate -c ajv-formats -s schemas/envelope.3.3.schema.json -d "tests/conformance/envelope/positive/*.json" --strict=true
      - name: Validate envelope: negative (expect fail)
        run: bash scripts/validate_negative.sh schemas/envelope.3.3.schema.json tests/conformance/envelope/negative
      - name: Validate route: positive
        run: npx ajv validate -c ajv-formats -s schemas/route.1.0.schema.json -d "tests/conformance/route/positive/*.json" --strict=true
      - name: Validate route: negative (expect fail)
        run: bash scripts/validate_negative.sh schemas/route.1.0.schema.json tests/conformance/route/negative
      - name: Build precompiled validators
        run: node scripts/build_validators.mjs
      - name: Conformance via precompiled validators
        run: node scripts/run_conformance_precompiled.mjs
      - name: Scan fixture expectations
        run: npm run test:fixtures:scan
      - name: Conformance report (NDJSON)
        run: node scripts/conformance_report.cjs
      - name: Run full conformance suite
        run: npm run conformance:all
      - name: Run smoke tests
        run: npm run smoke
      - name: Freeze schema fingerprints (if updated)
        run: npm run schema:hash
      - name: Check schema fingerprints
        run: npm run schema:check

      - name: Upload conformance artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conformance-artifacts
          path: build/reports/
      - name: Upload schema fingerprints
        uses: actions/upload-artifact@v4
        with:
          name: schema-fingerprints
          path: schemas/SCHEMA_FINGERPRINTS.json

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [conformance]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node
